### ISSUE TITLE
No longer builds on Mint 22.2

### ISSUE THREAD

**Issue by laperp0** [hanatos/vkdt#211]
Building via makefile no longer succeeds for commits after 50d43123f82bb1879ca8818ca2017da7cf959d5c on Linux Mint 22.2. Building on later commits always ends with the following:

>  pipe/modules/o-vid/main.c:121:7: error: call to undeclared function 'avcodec_get_supported_config'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  121 |       avcodec_get_supported_config(
          |       ^
pipe/modules/o-vid/main.c:121:7: note: did you mean 'avcodec_get_hw_config'?
/usr/include/x86_64-linux-gnu/libavcodec/codec.h:372:24: note: 'avcodec_get_hw_config' declared here
  372 | const AVCodecHWConfig *avcodec_get_hw_config(const AVCodec *codec, int index);
          |                        ^

> pipe/modules/o-vid/main.c:123:11: error: use of undeclared identifier 'AV_CODEC_CONFIG_SAMPLE_FORMAT'
  123 |           AV_CODEC_CONFIG_SAMPLE_FORMAT,
          |           ^

> pipe/modules/o-vid/main.c:132:11: error: use of undeclared identifier 'AV_CODEC_CONFIG_SAMPLE_RATE'
  132 |           AV_CODEC_CONFIG_SAMPLE_RATE,
          |           ^

**Comment by ptilopteri** [comment]
* johannes hanika ***@***.***> [12-05-25 08:21]:
> hanatos left a comment (hanatos/vkdt#211)
> 
> this is about newer versions of ffmpeg which deprecate the old code. i
> updated according to their recommendations, now it requires either a
> recent copy of ffmpeg's libraries, or to build without video support
> (see ptilopteri's post above).

yes, I had upgrades for ffmpeg-7-7.1.2-1699.3.pm.84.x86_64 and
libheif-ffmpeg-1.20.2-1699.5.pm.144.x86_64 yesterday and can now build
using my script with the exported "VKDT" comments removed.  :)


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc
